# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       pv
Summary:    Monitor the progress of data through a pipe
Version:    1.4.6
Release:    1
Group:      Development/Tools
License:    Artistic 2.0
URL:        http://www.ivarch.com/programs/pv.shtml
Source0:    http://www.ivarch.com/programs/sources/pv-1.4.6.tar.bz2
Source100:  pv.yaml
BuildRequires:  gettext


%description
PV ("Pipe Viewer") is a tool for monitoring the progress of data through a
pipeline.  It can be inserted into any normal pipeline between two processes
to give a visual indication of how quickly data is passing through, how long
it has taken, how near to completion it is, and an estimate of how long it
will be until completion.




%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
[ -n "$RPM_BUILD_ROOT" -a "$RPM_BUILD_ROOT" != / ] && rm -rf "$RPM_BUILD_ROOT"
mkdir -p "$RPM_BUILD_ROOT"%{_bindir}
mkdir -p "$RPM_BUILD_ROOT"%{_mandir}/man1
mkdir -p "$RPM_BUILD_ROOT"/usr/share/locale

make DESTDIR="$RPM_BUILD_ROOT" install

# << install post
%find_lang %{name}
%check
# >> check
make test
# << check






%files -f %{name}.lang
%defattr(-,root,root,-)
# >> files
%defattr(-, root, root)
%{_bindir}/%{name}
%{_mandir}/man1/%{name}.1.gz
%doc README doc/NEWS doc/TODO doc/COPYING
# << files


